import Link from "next/link";

import type { DraftListRow } from "@/server/services/content-draft";
import { DemoBadge } from "@/components/metrics/primitives";
import { StatusBadge, humanize } from "@/components/diagnosis/primitives";

/**
 * The drafts of a website, one row each (M4.4 §2). Every state is written
 * as a word - "Review requested", "Blocking", "Newer brief v3" - so a row
 * reads the same in a screenshot as on the screen.
 */
export function DraftsTable({
  rows,
  websiteId,
  isDemo,
}: {
  rows: DraftListRow[];
  websiteId: string;
  isDemo: boolean;
}) {
  return (
    <div className="border-border overflow-x-auto rounded-lg border">
      <table className="w-full text-sm">
        <thead className="bg-muted/40 text-muted-foreground text-left text-xs tracking-wide uppercase">
          <tr>
            <th scope="col" className="px-3 py-2 font-medium">
              Work item
            </th>
            <th scope="col" className="px-3 py-2 font-medium">
              Type
            </th>
            <th scope="col" className="px-3 py-2 font-medium">
              Brief
            </th>
            <th scope="col" className="px-3 py-2 font-medium">
              Status
            </th>
            <th scope="col" className="px-3 py-2 font-medium">
              Revision
            </th>
            <th scope="col" className="px-3 py-2 font-medium">
              Findings
            </th>
            <th scope="col" className="px-3 py-2 font-medium">
              Updated
            </th>
          </tr>
        </thead>
        <tbody className="divide-border divide-y">
          {rows.map((row) => (
            <tr key={row.id} className="align-top">
              <td className="px-3 py-2">
                <Link
                  href={`/websites/${websiteId}/content/${row.workItemId}/draft?draft=${row.id}`}
                  className="font-medium hover:underline"
                >
                  {row.currentTitle ?? row.workItemTitle}
                </Link>
                <div className="text-muted-foreground flex flex-wrap items-center gap-2 text-xs">
                  <span>{row.workItemTitle}</span>
                  {isDemo ? <DemoBadge /> : null}
                </div>
              </td>
              <td className="px-3 py-2 whitespace-nowrap">
                {row.contentType ? humanize(row.contentType) : "—"}
                <div className="text-muted-foreground text-xs">{humanize(row.workItemType)}</div>
              </td>
              <td className="px-3 py-2 whitespace-nowrap">
                <span className="font-mono text-xs">v{row.briefVersion}</span>
                {row.briefMismatch ? (
                  <div className="text-xs text-amber-800 dark:text-amber-300">
                    Newer brief v{row.briefMismatch.approvedVersion} approved
                  </div>
                ) : null}
              </td>
              <td className="px-3 py-2">
                <div className="flex flex-wrap items-center gap-1.5">
                  <StatusBadge status={row.status} />
                  {row.awaitingReview ? (
                    <span className="rounded-full bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-900 dark:bg-amber-900/40 dark:text-amber-200">
                      Review requested
                    </span>
                  ) : null}
                </div>
              </td>
              <td className="px-3 py-2 whitespace-nowrap">
                {row.currentRevisionNumber ? (
                  <>
                    <span className="font-mono text-xs">v{row.currentRevisionNumber}</span>
                    <div className="text-muted-foreground text-xs">
                      {row.authorKind === "AI"
                        ? "Generated by AI"
                        : row.authorKind === "HUMAN"
                          ? "Edited by a person"
                          : "Author not recorded"}
                      {row.revisionCount > 1 ? ` · ${row.revisionCount} revisions` : ""}
                    </div>
                  </>
                ) : (
                  <span className="text-muted-foreground text-xs">No revision yet</span>
                )}
              </td>
              <td className="px-3 py-2 whitespace-nowrap">
                {row.currentRevisionNumber ? (
                  <>
                    {row.blocking ? (
                      <span className="inline-flex items-center rounded border border-red-300 px-1.5 py-0.5 text-[11px] font-medium tracking-wide text-red-800 uppercase dark:border-red-900 dark:text-red-300">
                        Blocking
                      </span>
                    ) : null}
                    <div className="text-muted-foreground text-xs">
                      {row.findings.blocking} blocking · {row.findings.warning} warning ·{" "}
                      {row.findings.info} note
                    </div>
                  </>
                ) : (
                  <span className="text-muted-foreground text-xs">—</span>
                )}
              </td>
              <td className="text-muted-foreground px-3 py-2 text-xs whitespace-nowrap">
                {row.updatedAt.toLocaleString("en-GB")}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
