import { shortHash } from "@/lib/content/draft-ux";

/**
 * Who wrote a revision, based on which brief, using which evidence
 * (M4.4 §7), and what review did with it (M4.5). One panel for both kinds
 * of author: a generated revision shows the provider, model, agent, prompt
 * and schema versions, the sealed package with its policy and context
 * version; a hand-written one shows the person, the revision it was written
 * from, and the change summary. Above both sit the brief version, the work
 * item and the decision that started it. The Review block reads from the
 * ContentDraftReview row: who asked, who decided, what exactly, and
 * whether the approval still stands. Long strings are shortened on the
 * face and kept in full in a title.
 */

export type ProvenanceRevision = {
  revisionNumber: number;
  basedOnRevisionNumber: number | null;
  changeSummary: string;
  createdAt: Date;
  contentHash: string;
  wordCount: number | null;
  generationToken: string | null;
  createdByUserId: string | null;
  createdBy: { email: string } | null;
  createdByAiRun: {
    id: string;
    provider: string;
    model: string;
    promptTemplateVersion: number | null;
    outputSchemaVersion: string;
    createdAt: Date;
  } | null;
  evidencePackage: {
    id: string;
    contentHash: string;
    sealedAt: Date | null;
    evidenceCount: number;
    contextVersionId: string | null;
    retrievalPolicy: { name: string; version: number } | null;
  } | null;
};

export type ProvenanceLineage = {
  briefVersion: number;
  briefSuperseded: boolean;
  workItem: { title: string; type: string } | null;
  recommendation: { title: string } | null;
  decision: { decision: string; decidedBy: string; decidedAt: Date } | null;
};

/** The review cycle that concerns this revision, from its ContentDraftReview row. */
export type ProvenanceReview = {
  status: "REQUESTED" | "APPROVED" | "RETURNED" | "INVALIDATED";
  revisionNumber: number;
  revisionHash: string;
  briefVersion: number;
  requestedBy: string | null;
  requestedAt: Date;
  decidedBy: string | null;
  decidedAt: Date | null;
  note: string | null;
  selfDecided: boolean;
  briefSupersededAtDecision: boolean;
  briefMismatchAcknowledged: boolean;
  invalidatedReason: string | null;
  /** For APPROVED: the draft's standing approval still rests on this row. */
  current: boolean;
};

export function AuthorLabel({
  revision,
  viewerUserId,
}: {
  revision: Pick<ProvenanceRevision, "createdByAiRun" | "createdBy" | "createdByUserId">;
  viewerUserId?: string;
}) {
  if (revision.createdByAiRun) {
    return (
      <span className="inline-flex items-center rounded-md border border-sky-700/40 px-2 py-0.5 text-xs font-medium text-sky-700 dark:text-sky-400">
        Generated by AI
      </span>
    );
  }
  const who =
    revision.createdBy &&
    (viewerUserId && revision.createdByUserId === viewerUserId ? "you" : revision.createdBy.email);
  return (
    <span className="border-border inline-flex items-center rounded-md border px-2 py-0.5 text-xs font-medium">
      {who ? `Edited by ${who}` : "Author not recorded"}
    </span>
  );
}

function Row({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="grid gap-x-3 gap-y-0.5 px-3 py-2 sm:grid-cols-[9rem_1fr]">
      <dt className="text-muted-foreground text-xs">{label}</dt>
      <dd className="min-w-0 text-sm break-words">{children}</dd>
    </div>
  );
}

function Mono({ value, keep = 12 }: { value: string; keep?: number }) {
  return (
    <span className="font-mono text-xs" title={value}>
      {shortHash(value, keep)}
    </span>
  );
}

function at(date: Date | null | undefined): string {
  return date ? date.toLocaleString("en-GB") : "—";
}

const INVALIDATION_WORDS: Record<string, string> = {
  content_changed: "the content changed after review was requested",
  draft_superseded: "the draft was superseded by a draft on a newer brief",
};

/** What review did with a revision, in words (M4.5). */
export function ReviewBlock({ review }: { review: ProvenanceReview }) {
  return (
    <>
      <Row label="Review requested">
        {review.requestedBy ?? "Not recorded"} on {at(review.requestedAt)}
        <span className="text-muted-foreground">
          {" "}
          · for revision {review.revisionNumber} · <Mono value={review.revisionHash} /> · Brief v
          {review.briefVersion}
        </span>
      </Row>
      {review.status === "APPROVED" ? (
        <>
          <Row label="Approved">
            {review.decidedBy ?? "Not recorded"} on {at(review.decidedAt)}
            <span className="text-muted-foreground">
              {" "}
              · exactly revision {review.revisionNumber}
              {review.selfDecided ? " · approved by its own author" : ""}
            </span>
          </Row>
          <Row label="Approval note">
            {review.note ?? <span className="text-muted-foreground">None given</span>}
          </Row>
          {review.briefSupersededAtDecision ? (
            <Row label="Newer brief">
              A newer brief version had been approved by then;{" "}
              {review.briefMismatchAcknowledged
                ? `the reviewer acknowledged it and approved against Brief v${review.briefVersion}.`
                : "not acknowledged."}
            </Row>
          ) : null}
          <Row label="Standing">
            {review.current ? (
              <span className="font-medium">
                This approval is current: the draft is ready for QA.
              </span>
            ) : (
              <span>
                <span className="font-medium">Approval no longer current.</span>{" "}
                <span className="text-muted-foreground">
                  The draft was reopened or superseded after this approval; it stays in history.
                </span>
              </span>
            )}
          </Row>
        </>
      ) : review.status === "RETURNED" ? (
        <Row label="Returned to drafting">
          {review.decidedBy ?? "Not recorded"} on {at(review.decidedAt)}
          {review.selfDecided ? (
            <span className="text-muted-foreground"> · by its own author</span>
          ) : null}
          {review.note ? <span className="block">“{review.note}”</span> : null}
        </Row>
      ) : review.status === "INVALIDATED" ? (
        <Row label="Request withdrawn">
          {INVALIDATION_WORDS[review.invalidatedReason ?? ""] ?? "the request no longer applies"}
          <span className="text-muted-foreground">. Nothing was decided.</span>
        </Row>
      ) : (
        <Row label="Decision">
          <span className="text-muted-foreground">Awaiting an SEO lead, admin or owner.</span>
        </Row>
      )}
    </>
  );
}

export function ProvenancePanel({
  revision,
  lineage,
  review,
  viewerUserId,
}: {
  revision: ProvenanceRevision;
  lineage: ProvenanceLineage;
  review?: ProvenanceReview | null;
  viewerUserId?: string;
}) {
  const run = revision.createdByAiRun;
  const pkg = revision.evidencePackage;

  return (
    <section aria-labelledby="provenance-heading" className="space-y-3">
      <h2 id="provenance-heading" className="text-sm font-medium">
        Provenance
        <span className="text-muted-foreground font-normal">
          {" "}
          · revision {revision.revisionNumber}
        </span>
      </h2>
      <div className="flex flex-wrap items-center gap-2">
        <AuthorLabel revision={revision} viewerUserId={viewerUserId} />
        <span className="text-muted-foreground text-xs">
          {revision.createdAt.toLocaleString("en-GB")}
        </span>
      </div>

      <dl className="divide-border border-border divide-y rounded-lg border">
        <Row label="Based on">
          {revision.basedOnRevisionNumber
            ? `Revision ${revision.basedOnRevisionNumber}`
            : "Nothing — the first revision"}
        </Row>
        <Row label="Change summary">{revision.changeSummary}</Row>
        <Row label="Brief">
          Brief v{lineage.briefVersion}
          {lineage.briefSuperseded ? (
            <span className="text-muted-foreground"> (since superseded)</span>
          ) : null}
        </Row>
        {lineage.workItem ? (
          <Row label="Work item">
            {lineage.workItem.title}
            <span className="text-muted-foreground">
              {" "}
              · {lineage.workItem.type.toLowerCase().replace(/_/g, " ")}
            </span>
          </Row>
        ) : null}
        {lineage.recommendation ? (
          <Row label="Recommendation">{lineage.recommendation.title}</Row>
        ) : null}
        {lineage.decision ? (
          <Row label="Decision">
            {lineage.decision.decision.toLowerCase().replace(/_/g, " ")} by{" "}
            {lineage.decision.decidedBy} on {lineage.decision.decidedAt.toLocaleDateString("en-GB")}
          </Row>
        ) : null}

        {run ? (
          <>
            <Row label="Provider · model">
              {run.provider} · {run.model}
            </Row>
            <Row label="Agent">Content draft (CONTENT_DRAFT · GENERATE_DRAFT)</Row>
            <Row label="Prompt · schema">
              prompt v{run.promptTemplateVersion ?? "?"} · output schema v{run.outputSchemaVersion}
            </Row>
            <Row label="Generated at">{run.createdAt.toLocaleString("en-GB")}</Row>
            <Row label="AI run">
              <Mono value={run.id} keep={8} />
            </Row>
          </>
        ) : (
          <Row label="Written by">
            {revision.createdBy?.email ?? "Not recorded"}
            <span className="text-muted-foreground">
              {" "}
              · by hand, against the facts approved at the time
            </span>
          </Row>
        )}

        {pkg ? (
          <>
            <Row label="Evidence package">
              <Mono value={pkg.contentHash} />
              <span className="text-muted-foreground">
                {" "}
                · {pkg.evidenceCount} records · {pkg.sealedAt ? "sealed" : "not sealed"}
              </span>
            </Row>
            <Row label="Retrieval policy">
              {pkg.retrievalPolicy
                ? `${pkg.retrievalPolicy.name} v${pkg.retrievalPolicy.version}`
                : "Not recorded"}
            </Row>
            <Row label="Context version">
              {pkg.contextVersionId ? (
                <Mono value={pkg.contextVersionId} keep={8} />
              ) : (
                <span className="text-muted-foreground">None approved when assembled</span>
              )}
            </Row>
          </>
        ) : null}

        <Row label="Content hash">
          <Mono value={revision.contentHash} />
        </Row>
        {revision.generationToken ? (
          <Row label="Request token">
            <Mono value={revision.generationToken} keep={8} />
          </Row>
        ) : null}
        <Row label="Length">{revision.wordCount ?? "?"} words</Row>

        {review ? <ReviewBlock review={review} /> : null}
      </dl>
    </section>
  );
}
